// src/theme/styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    //flex: 1,
    backgroundColor: "#fff",
    paddingHorizontal: 24,
    //justifyContent: "center",
    padding: 20,
    paddingTop: 40, 
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 32,
    textAlign: "center",
  },
  sectionTitle: { fontSize: 18, fontWeight: "600", marginTop: 30, marginBottom: 10, color: "#000" },
  label: { color: "#666", fontWeight: "600" },
  value: { color: "#000", fontSize: 16 },
  infoBox: { marginBottom: 20 },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 14,
    borderRadius: 8,
    marginBottom: 16,
    fontSize: 16,
    color: "#000",
  },
  button: {
    backgroundColor: "#000",
    padding: 16,
    borderRadius: 8,
    marginBottom: 12,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    textAlign: "center",
  },
  link: {
    color: "#666",
    fontSize: 14,
    textAlign: "center",
    marginTop: 10,
  },
  socialButton: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "center",
  borderWidth: 1,
  borderColor: "#ccc",
  padding: 14,
  borderRadius: 8,
  marginBottom: 12,
  backgroundColor: "#fff",
},
logoutButton: {
    backgroundColor: "#c00",
},
socialButtonText: {
  color: "#000",
  fontSize: 16,
  marginLeft: 8,
},
  tabBar: {
    position: 'absolute',
    height: 70,
    paddingBottom: 10,
    paddingTop: 10,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: '#fff',
    elevation: 5,
  },
  floatingButton: {
    backgroundColor: '#3b82f6',
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 40,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 5,
    elevation: 5,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    flexDirection: "row",
    padding: 16,
    marginBottom: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
    location: {
    fontSize: 14,
    color: "#666",
    marginBottom: 4,
  },
  attendees: {
    fontSize: 12,
    color: "#888",
    marginTop: 4,
  },
  dateBox: {
    backgroundColor: "#eee",
    borderRadius: 12,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    width: 60,
  },
  dateDay: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#000",
  },
  dateMonth: {
    fontSize: 12,
    fontWeight: "600",
    color: "#555",
  },
  category: {
  fontSize: 12,
  color: "#999",
  marginBottom: 4,
},

});
